### ISSUE TITLE
only work with 1.05 version

### ISSUE THREAD

**Issue by spphinslove** [SecUSo/privacy-friendly-pedometer#100]
Only. 1.05 can count step,device xiaomi 10t.os:arrowos 12.any log can I upload here?

**Comment by sleep-yearning** [comment]
The reason is very likely more recent Android SDK versions with which the later versions of the app are built. Since Android changes a lot over versions, behaviors also change and developers have to amend code. However, some APIs just work differently. 
Did you try all the step-counting methods (accelerometer, step counter, step detector) in the 2.4 version?

Also, if you want to provide logs, you can create something like a pastebin in your github and reply with a link to that.

**Comment by sleep-yearning** [comment]
Closing since no answer and multiple new versions since then, feel free to reopen if it continues to be an issue with newest versions.
