### ISSUE TITLE
Is it possible to remove Location permission?

### ISSUE THREAD

**Issue by thelou1s** [SecUSo/privacy-friendly-pedometer#119]
As location permission is a not privacy friendly, Is it possible to remove Location permission?

**Comment by sleep-yearning** [comment]
Hi thelou1s, I get that location permission is not privacy friendly in general perception, however there are multiple reasons why it is not a privacy risk here:
- in general on newer Android OS Versions (I think since Marshmallow 6.0) you have to agree before the app can even use location data, with the option of just not allowing it and still using the app.
- In this app, the location is only used for one function: Movement speed assessment, meaning if you don't use that, it won't even try to use location data
- Our apps are built to be privacy friendly, in this case pedometer does not send any data to us or someone else, everything is on your phone


I hope you can see why I don't see the need to remove the permission (even if it would mean that only one function got removed), since there is hardly any privacy risk in my opinion.
